### PR TITLE
Replace node-fetch with undici

### PR DESCRIPTION
**Pull request by DaInfLoop**
Make sure the node-fetch install command is the cjs tag version, otherwise the code on line 195-233 will throw errors!

### CODE REVIEW

**Comment by xHyroM** [comment]
I'd probably swap node-fetch to undici straight away, because djs will be switching to undici as well.

**Comment by DaInfLoop** [comment]
> I'd probably change node-fetch to undici straight away, because djs will be switching to undici as well.

I'll have a look at it now, then I'll edit the page based on it.

**Comment by N0ahMC** [comment]
Is there a reason you used undici instead of axios? Just wondering, because I believe it's usually preferred.

**Comment by suneettipirneni** [comment]
> Is there a reason you used undici instead of axios? Just wondering, because I believe it's usually preferred.

Axios is one of the slowest performing http request libraries which doesn't make it a great candidate for an api wrapper that makes a lot of requests at once. undici seems to be one of the fastest due to its many optimizations. In addition, it provides many spec compliant structures like FormData that are cross compatible with the web standards.

**Comment by N0ahMC** [comment]
> > Is there a reason you used undici instead of axios? Just wondering, because I believe it's usually preferred.
> 
> Axios is one of the slowest performing http request libraries which doesn't make it a great candidate for an api wrapper that makes a lot of requests at once. undici seems to be one of the fastest due to its many optimizations. In addition, it provides many spec compliant structures like FormData that are cross compatible with the web standards. (And it'll be built into node soon)

Ahhh that makes sense, thanks!

**Review by almostSouji — COMMENTED** [review]
Why not stick to the fetch API with #fetch and #json? Is there a reason I'm missing?

**Comment by DaInfLoop** [comment]
Why not stay with it?

The fetch API part of undici is still experimental, so until it's stable,
may aswell use `request()`

**Comment by almostSouji** [comment]
I see! So then this mostly needs to get off of CI red

**Comment by DaInfLoop** [comment]
> I see! So then this mostly needs to get off of CI red

Tried to fix it, need approval for the ESLint action (which is why I asked for review)

**Comment by DaInfLoop** [comment]
Just went to check deploy preview and saw most of the code highlighting had messed up, if anyone could fix it because I'm busy right now I'd be glad.

**Comment by GodderE2D** [comment]
There's also a node-fetch occurrence here: https://github.com/discordjs/guide/blob/main/code-samples/additional-info/rest-api/13/index.js, would that also need to be changed to undici?

**Comment by DaInfLoop** [comment]
Probably, when I get the chance I'll update that page too.

**Comment by imranbarbhuiya** [comment]
Change the title and description as this pr no longer 3dits node-fetch install command.

**Comment by almostSouji** [comment]
applied in https://github.com/discordjs/guide/commit/f8479528204893b19202903055799021a61ff03a

**Pull request closed without merging**
