### PR TITLE
Use the dev version

### PR DESCRIPTION
**Pull request by theblobscp**
This will properly install the version 13

### CODE REVIEW

**Comment by Megatank58** [comment]
The guide is for v13 not dev version so after v13 releases this would be needed to changed again

**Comment by theblobscp** [comment]
True, but for now will it still be outdated?

**Comment by PenPow** [comment]
> True, but for now will it still be outdated?

Yes, but this guide is for V13 when it releases, which hopefully _fingers crossed_should be fairly soon (all dependant on discord). There is no reason to make a PR changing this, when it will shortly be reverted.

**Comment by theblobscp** [comment]
Ok, I see your point

**Pull request closed without merging**
