### PR TITLE
fix: typo in "Advanced deployment" example

### PR DESCRIPTION
**Pull request by pixxies**
**Please describe the changes this PR makes and why it should be merged:**

Typo in the example. Should say "successfully".

### CODE REVIEW

**Review by SuperchupuDev — COMMENTED** [review]
Maybe also remove the dot at the end for consistency with the console.log above

**Comment by pixxies** [comment]
I added a period to the console.log above it since it seems that's the way most console.logs are done throughout the guide.

**Comment by SuperchupuDev** [comment]
> I added a period to the console.log above it since it seems that's the way most console.logs are done throughout the guide.

oh so you added a new dot, that's fine then 

you should probably pr this on discord.js's readme once this is merged

**Review by SuperchupuDev — APPROVED** [review]

**Comment by pixxies** [comment]
> > I added a period to the console.log above it since it seems that's the way most console.logs are done throughout the guide.
> 
> oh so you added a new dot, that's fine then
> 
> you should probably pr this on discord.js's readme once this is merged

Already done and [merged](https://github.com/discordjs/discord.js/pull/6292) on discord.js

**Pull request merged**
