### PR TITLE
refactor: Updating images

### LINKED ISSUE #575: Update website images to latest
**Is your feature request related to a problem? Please describe.**

It's been a while and the images in the guide (for example, the Discord Developer Portal, the Authorize pages, etc.) look outdated compared to now. It would be nice if all images were updated to show the current layouts of the websites.

**Examples**

The image displayed in the guide:

The image displayed in the guide

The current layout of the website:

Current Layout

**Describe the solution you'd like**

I'd like the images to be updated to show the current layouts of the websites.

### LINKED ISSUE #587: Rename all images and remove stale images for better quality.
**Is your feature request related to a problem? Please describe.**

A lot of the images are named like `ooaOAeu.png` or `qEIaiam.png`. It would be better if they had names like `sample-embed.png` and `avatar-cmd-demo.png`. Some other images in the repo are extremely out of date [like this one](https://raw.githubusercontent.com/discordjs/guide/master/guide/images/E1CZqFT.png) and [this one](https://raw.githubusercontent.com/discordjs/guide/master/guide/images/jnE3tVM.png).

**Describe the solution you'd like**

I'd like the images to be renamed to something related and meaningful instead of random characters. I'd also like it if the outdated (unused) images are removed/replaced as necessary.

**Additional context**
This will be added as an addition to #576 if approved.

### PR DESCRIPTION
**Pull request by WiseDevHelper**
**Please describe the changes this PR makes and why it should be merged:**

Closes #575 and resolves #587.

[Demo](https://deploy-preview-576--discordjs-guide.netlify.app/)

This PR replaces all outdated `images` in the guide and moves all images into each module's own `images` subfolder. The goal of this PR is to make it easier for the reader to follow along, and also makes accessing images simpler for future contributors. Currently, all the images are located in a separate `images` folder, which makes accessing images arduous. Also, most of the images are not up to date, which might confuse the reader.

**Status**
- [x] Move images to the respective folder.
  - [x] Additional info
  - [x] Command handling
  - [x] Event handling
  - [x] Commando (No images)
  - [x] Creating your bot
  - [x] Improving dev environment (No images)
  - [x] Keyv (No images)
  - [x] Miscallaneous
  - [x] OAuth2
  - [x] Popular Topics
  - [x] Preparations
  - [x] Sequilize
  - [x] Sharding (No images)
  - [x] Voice

<br>

- [x] Update images
  - [x] bot-in-memberlist.png
  - [x] bot-auth-page.png
  - [x] bot-authorized.png
  - [x] search.png
  - [x] send.png
  - [x] create-app.png
  - [x] create-bot.png
  - [x] created-bot.png

### CODE REVIEW

**Comment by WiseDevHelper** [comment]
Hi @Danktuary, just wanted to inform you that the PR is ready to merge. If there is anything else that I have yet to change, please alert me. Thanks.

**Comment by almostSouji** [comment]
Resolve conflicts from the grammar and formatting PR, please double-check in case I messed something up here (sorry for the inconvenience)

**Review by Danktuary — COMMENTED** [review]
Aside what Souji mentioned, I'll add just this before merging: `guide/oauth2/images/authorize-app-page.png` should use the User username and d.js avatar

**Comment by WiseDevHelper** [comment]
@Danktuary updated the image as requested. 👍

**Review by Danktuary — APPROVED** [review]

**Pull request merged**
