### PR TITLE
Update useful-packages.md

### PR DESCRIPTION
**Pull request by Purukitto**
**Please describe the changes this PR makes and why it should be merged:**
Since in Winston's case we are showing sort of the complete code example, I think it's important to the module import statement as well.

### CODE REVIEW

**Comment by Purukitto** [comment]
Also I do feel it will be helpful to add the `npm install` commands to all these packages, should I those too? Is there any specific reason why they weren't included?

**Comment by monbrey** [comment]
Given that each package has a link to it's documentation I don't think its necessary for us to cover how to install them all.

People who are looking to incorporate additional third party libraries into their code should know how to install packages already.

**Comment by Purukitto** [comment]
@monbrey as I said it is def not necessary but it's just adding a extra step for the user. In that light we might as well as not add the example since the documentations mentioned do already have examples as well. I just feel adding the install call would make it easier for the user to get started immediately.

**Comment by almostSouji** [comment]
> I just feel adding the install call would make it easier for the user to get started immediately.

Preventing this is precisely the purpose here.

The idea of this guide section is to give the user a very very brief impulse as to which packages might be a good addition to their project, if deemed useful. Readers definitely should check out the official documentation on how to install and use the package after seeing the entry in the guide, not just blindly and mindlessly copy and paste the example use case given here.

As part of this nudge towards reading the documentation a complete "resulting code" snippet as well as the package imports and setups are deliberately not included.

**Pull request closed without merging**
