### PR TITLE
fix: replace old interaction.reply code

### PR DESCRIPTION
**Pull request by megatank58**
**Please describe the changes this PR makes and why it should be merged:**

### CODE REVIEW

**Comment by tipakA** [comment]
While we're at it, might be worth to look through more than just what was brought up in discord.

https://github.com/discordjs/guide/blob/main/code-samples/popular-topics/reactions/13/awaiting-reactions.js#L15

**Comment by megatank58** [comment]
Oh woops, fixed

**Review by vitorlops — CHANGES_REQUESTED** [review]
Places that still need replace:
https://github.com/discordjs/guide/blob/4e84b88cc950d62e7b9a3ef90dcceba63a816c90/code-samples/popular-topics/reactions/13/basic-reacting.js#L17-L20
https://github.com/discordjs/guide/blob/032f56fa62da641e81810419ef353615051c189a/code-samples/popular-topics/reactions/13/basic-reacting.js#L17-L23
https://github.com/discordjs/guide/blob/032f56fa62da641e81810419ef353615051c189a/guide/popular-topics/collectors.md?plain=1#L69

**Comment by megatank58** [comment]
Made the changes, thanks!

**Review by almostSouji — APPROVED** [review]

**Pull request merged**
