### PR TITLE
Fixed Small Syntax Error With ping Example

### PR DESCRIPTION
**Pull request by shadowtime2000**
At line 52 there was an unnecessary comma

### CODE REVIEW

**Comment by PyroTechniac** [comment]
That comma is perfectly valid

**Comment by shadowtime2000** [comment]
How? There are no elements appearing in it afterward.

**Comment by iCrawl** [comment]
It's a stylistic choice.

**Comment by shadowtime2000** [comment]
There is really no point for that comma to exist.

**Comment by Fyko** [comment]
> 
> 
> There is really no point for that comma to exist.

It's required by the [eslint config](https://github.com/Danktuary/eslint-config-sora/blob/67a9352a3d780897854c7f6284d891f2d4c26e67/index.js#L29). So yes, there is a point.

**Comment by shadowtime2000** [comment]
Oh ok.

**Pull request closed without merging**
