### PR TITLE
Update fs.readdirSync() setup.

### PR DESCRIPTION
**Pull request by Hades6578**
fs.readdirSync() no longer functions without invoking the path to command folder via fs.realpathSync(), when you do not, it returns "Error: ENOENT: no such file or directory, scandir './commands'. " Simply requires that extra line to work properly.

**Please describe the changes this PR makes and why it should be merged:**
Took quite a while to attempt to get the code to find the file, originally deterred me from continuing to work on my bot.  I solved the problem through sheer luck.

### CODE REVIEW

**Comment by Hades6578** [comment]
Please let me know if this change is necessary or helpful.  If it's not relevant, I will remove this pull req.

**Comment by megatank58** [comment]
#1069 already does this and a few more changes

**Comment by Hades6578** [comment]
> #1069 already does this and a few more changes

I went back through the tutorial, and it does not appear as if the changes were actually pushed yet.  I also attempted to fix my error with the solution, but it produces a similar error.

**Comment by megatank58** [comment]
The guide should then just have it directly from the starting instead of having an update or note somewhere and all occurrences would need to be changed

**Comment by Hades6578** [comment]
> The guide should then just have it directly from the starting instead of having an update or note somewhere and all occurrences would need to be changed

Ok, how would I go about that? Or is that someone else's job?

**Comment by Hades6578** [comment]
Rewrote the lines, and more smoothly integrated the modified code.  Should be ready for merge, but please check to make sure you like the way I wrote it.

**Comment by almostSouji** [comment]
I am still not sure what this fixes? I cannot reproduce the issue you seem to be experiencing.

**Comment by Hades6578** [comment]
> I am still not sure what this fixes? I cannot reproduce the issue you seem to be experiencing.

Strange, I had the standard EONET error. I wonder why it isn’t coming up for you.

**Comment by almostSouji** [comment]
Until someone can reproduce and explain why exactly this is necessary, we won't implement this.

**Comment by Hades6578** [comment]
> Until someone can reproduce and explain why exactly this is necessary, we won't implement this.

Will attempt to recreate circumstances and attach screenshots of output.

**Pull request closed without merging**
