### PR TITLE
fix(reactions): fix interaction.reply() params

### PR DESCRIPTION
**Pull request by BaumianerNiklas**
**Please describe the changes this PR makes and why it should be merged:**

In the `popular-topics/reactions` section, there are multiple instances of `interaction.reply()` that wrongly use 2 parameters instead of just one. This PR fixes those.

### CODE REVIEW

**Comment by WiseDevHelper** [comment]
Doesn't #864 fix this?

**Comment by BaumianerNiklas** [comment]
As far as I can tell that PR only fixes similar issues in the Async/Await section of the guide, while this one only fixes them in the Reactions section. There may also still be other sections of the guide with these issues though

**Comment by Megatank58** [comment]
I can have these changes in my pr along with the async page if you would like or both pr can be merged, also only these two pages have the outdated code afaik

**Comment by BaumianerNiklas** [comment]
I dont really mind, if you want to you can add these changes to your PR and I'll close this one. I took a quick look at some other pages in the Popular Topics section when making this PR but didn't notice anything that needed to be changed

**Comment by Megatank58** [comment]
Hm alright then I'll just include these changes in the same pr

**Comment by Megatank58** [comment]
I have included these changes in #864

**Pull request closed without merging**
