### PR TITLE
destructure all properties in the sharding guide

### PR DESCRIPTION
**Pull request by UndecidedSource**
**Please describe the changes this PR makes and why it should be merged:**
Some of the snippets on the top of the guide have the variables destructured. This PR destructures the other variables too.

### CODE REVIEW

**Comment by Danktuary** [comment]
Could you update the file in the code-samples folder as well?

**Comment by UndecidedSource** [comment]
@Danktuary Updated code samples!

**Comment by Danktuary** [comment]
You edited the /extended/bot.js file as well instead of just the /getting-started/bot.js file. That file has other references to the Discord variable. It's fine to update that file but if you do, be sure to update the guide page as well.

**Comment by UndecidedSource** [comment]
@Danktuary I reverted my changes to /extended/bot.js

**Pull request merged**
