### PR TITLE
👾 replace right click -> right-click

### PR DESCRIPTION
**Pull request by Rnbsov**
**Please describe the changes this PR makes and why it should be merged:**
I think it will be slightly more correct

### CODE REVIEW

**Comment by megatank58** [comment]
Is this really necessary, looks just fine either way

**Comment by Rnbsov** [comment]
> Is this really necessary, looks just fine either way

I guess it will look more beautiful anyway

**Comment by megatank58** [comment]
I would argue both methods of writing it are common and this change is unnecessary

**Comment by almostSouji** [comment]
Even the various dictionaries aren't in unison about this, we'll keep it as-is

**Pull request closed without merging**
