### PR TITLE
rebrand: Imagine a guide

### PR DESCRIPTION
**Pull request by Danktuary**
**Please describe the changes this PR makes and why it should be merged:**

Guide v3! 🎉 ([Preview](https://i.imgur.com/iOWqlpW.png) | [Demo](https://deploy-preview-688--discordjs-guide.netlify.app/))

Preparing for discord.js v13 release by updating the site and removing old content.

New: 
- Theme made to match the [discord.js website](https://discord.js.org/)
- VuePress updated to [v2](https://github.com/vuepress/vuepress-next)
- vue-discord-message updated to [@discord-message-components/vue](https://github.com/Danktuary/discord-message-components/blob/main/packages/vue/README.md)

Removed:
- All v11 branch content and code samples
- Changes in v12 page

Currently using VuePress' default theme, there are a few limitations. Extending the layout components can fix them.
- Dark theme depends on your device's preferences, and does not save to storage when toggled
- Only the green and blurple themes are available right now; other themes and additions will be brought back later

### CODE REVIEW

**Comment by advaith1** [comment]
> Changes in v12 page

why was this removed? I thought it would be kept, to help people who still need to update their old code

**Comment by almostSouji** [comment]
> 
> 
> > Changes in v12 page
> 
> why was this removed? I thought it would be kept, to help people who still need to update their old code

v12 -> v13 alone is such a big jump that v11 -> v12 -> v13 would not be an approach we recommend. We've had v12 out for such a long time (and even v11 being broken for long) that a v11 -> v12 jump should be considered an edge case.

for those still wanting it v11 -> v12 will be archived (with their respective branching content) under it's own subdomain. V13 wil mark a fresh start since so much has changed (and we plan on moving over to deprecate message commands with discord developing interactions more and more.

**Comment by almostSouji** [comment]
the general idea of keycaps is interesting, however, looks quite out of place in the search bar, as it introduces yet another shape, weight, alignment, and font to the navbar.
image


This should probably scroll within the modal, rather than breaking out of it
image

**Comment by iCrawl** [comment]
IMO the animations on page switches are terribly slow and could be sped up a little bit. (Preferably completely removed but I guess we would disagree on this).

image

The currently selected item with the black text is horribly hard to read compared to the one below, maybe it should stay with the white font for this?

**Comment by WiseDevHelper** [comment]
IMO, The theme switcher (Dark/Light) search bar should be moved to the top right to match with the docs.

The line that separates line numbers from code disappears when the code is highlighted. I think it would be better if the line was still visible in the highlights or removed (Preferably the former). 
image

The inline code blocks are not easy to read, I think it should either match the current theme colour or be a preset but bright colour (like purple previously) or the white colour that the docs use. 
image

The links in the `Tips` and maybe the `Warning` boxes could be brighter or have a different colour altogether. The links `Danger` boxes are good, however.
image
image
image

Search results for removed pages still show up.
image

#### Though I see the guide's theme is made to match the docs', I'd highly recommend brightening up the colours since the guide is more for reading than the docs.

**Comment by Danktuary** [comment]
> the general idea of keycaps is interesting, however, looks quite out of place in the search bar, as it introduces yet another shape, weight, alignment, and font to the navbar.

I'd like to keep them but I'll try to style it better; the search input and modal aren't complete yet

> This should probably scroll within the modal, rather than breaking out of it 
> (confirmed firefox issue, tested on `89.0.2 (64-bit)`)

I'll try to fix this if possible

> IMO the animations on page switches are terribly slow and could be sped up a little bit. (Preferably completely removed but I guess we would disagree on this).

Personally I'd like to keep them, unsure about how others feel. I'll speed it up though

> The currently selected item with the black text is horribly hard to read compared to the one below, maybe it should stay with the white font for this?

Yeah, will fix

> IMO, The theme switcher (Dark/Light) search bar should be moved to the top right to match with the docs.

Unsure if I'll be able to do this properly due to how the default theme's HTML is written. Currently all edits are done through CSS, so sometimes styling gets limited. This will get fixed sooner or later though

> The line that separates line numbers from code disappears when the code is highlighted. I think it would be better if the line was still visible in the highlights or removed (Preferably the former). 

Will fix

> The inline code blocks are not easy to read, I think it should either match the current theme colour or be a preset but bright colour (like purple previously) or the white colour that the docs use. 

Will adjust

> The links in the `Tips` and maybe the `Warning` boxes could be brighter or have a different colour altogether. The links `Danger` boxes are good, however.

Will adjust

> Search results for removed pages still show up.

This is due to the docsearch plugin using the guide's current search index, so until this PR gets merged into master, it'll still show them.

> #### Though I see the guide's theme is made to match the docs', I'd highly recommend brightening up the colours since the guide is more for reading than the docs.

The color will be kept to match the d.js site but maybe once I eventually add back theme selection, I'll add an alternate blurple scheme

**Comment by Danktuary** [comment]
So for the time being, I'll have to leave the theme toggle button and search input aligned to the left due to how VitePress' default theme is structured. I'll adjust the mobile nav a bit better since the items are off-center, and also try to fix the search modal scroll but, but that'll be it for now.

I'll make a separate PR to create a custom theme to fix these things and more at a later date.

**Review by almostSouji — APPROVED** [review]
can't find anything off anymore 👍

**Review by iCrawl — APPROVED** [review]
🚀

**Review by kyranet — APPROVED** [review]
Other than the left nav not having some padding (like the main website does), this is truly a work of art, I love it ❤️

**Pull request merged**
