### PR TITLE
A Note for STEP-BY-STEP Users

### PR DESCRIPTION
**Pull request by Tarvey**
A Note, for S-B-S Users thats quite hard for beginners

### CODE REVIEW

**Comment by jaw0r3k** [comment]
i think it's useless

**Comment by megatank58** [comment]
This feels like basic JavaScript, if anything and if really, it should be added to the errors page and not here, you should not be adding random commas

**Comment by Tarvey** [comment]
> This feels like basic JavaScript, if anything and if really, it should be added to the errors page and not here, you should not be adding random commas

random commas? if you follow step by step, in one of the code blocks, theres a comma, thats why

**Comment by Jiralite** [comment]
This is far too basic.

**Comment by monbrey** [comment]
So fix the code block if there's a comma that shouldn't be there?

Don't add a section to explain if it was wrong, make it right.

**Pull request closed without merging**
