### PR TITLE
update guide

### LINKED ISSUE #1238: Hard transition from handling section to further command examples
In the "handling commands" section we attach the data to be deployed to the respective export, so it is packed with its execution.
The slash command section provides more examples of using command builders, but defines them as a `const` for demonstration purposes.

It is expected that you still just use them as demonstrated in the other guide section. Just define it on the respective export, in the `data` key, as before.

We could potentially remedy this by using it in the same context as previous sections, for example

```js
module.exports = {
	data: new SlashCommandBuilder()
	    .setName('echo')
	    .setDescription('Replies with your input!')
	    .addStringOption(option =>
		    option.setName('input')
			    .setDescription('The input to echo back')
			    .setRequired(true));
	async execute(/* ... */) {
		// ...
	},
};
```

_Originally posted by @almostSouji in https://github.com/discordjs/guide/issues/1237#issuecomment-1229525205_

### PR DESCRIPTION
**Pull request by lolollllo**
**Please describe the changes this PR makes and why it should be merged:**
- Removes the `Parsing Mention Arguments` page - https://github.com/discordjs/guide/issues/1262#issuecomment-1264759016
- Resolves #1238

### CODE REVIEW

**Comment by megatank58** [comment]
The sidebar line https://github.com/lolollllo/guide/blob/main/guide/.vuepress/sidebar.ts#L88 needs to be removed here

**Comment by jaw0r3k** [comment]
andu should fix syntax bc eslint screams

**Comment by jaw0r3k** [comment]
and idk if PermissionsBitField.Flags must be changed to PermissionFlagsBits both are working

**Review by almostSouji — CHANGES_REQUESTED** [review]
- Please only cover one issue per PR to ease reviewing and implementation (this is about 3 PRs in one)
- Use a semantic PR title not "update guide".
- #1238 is already covered by a comprehensive rewrite of that section at https://github.com/discordjs/guide/pull/1281 and will further be streamlined in the rewrite.
- Please run the lint script before committing your changes, as described in https://github.com/discordjs/guide/blob/main/CONTRIBUTING.md

If you wish to still resolve the parsing mention args removal, please adapt the PR accordingly

**Comment by almostSouji** [comment]
> If you wish to still resolve the parsing mention args removal, please adapt the PR accordingly

Actually will need to open a new one, since you used a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) (resolves) and there is no way to unlink an issue.

**Pull request closed without merging**
