### PR TITLE
refactor: production build uses webpack and shiki

### PR DESCRIPTION
**Pull request by DET171**
**Please describe the changes this PR makes and why it should be merged:**
Webpack can bundle code that targets older browsers while vite cannot. Shiki also has higher fidelity than prismjs, as mentioned in the VuePress docs.
P.S. The VuePress 2 docs also use the same configuration as stated above.

### CODE REVIEW

**Comment by DET171** [comment]
Removed line numbers for code blocks as well as it looks wrong and bad to on mobile (the line numbers are already a bit off if the code blocks is a few hundred lines long).
Let’s wait for VuePress to fix this first?

**Comment by almostSouji** [comment]
I have absolutely no idea what you mean by 
> it looks wrong and bad to on mobile
Looks good on my end

**Comment by DET171** [comment]
This:
B69B1F22-1303-45DD-91A1-A265B314FB3F

**Comment by PenPow** [comment]
I can't reproduce on Android (Longer lines just require horizontal scroll).

However, I can reproduce on IOS (iPhone 8).

**Comment by Danktuary** [comment]
@DET171 @PenPow Could you guys provide your iOS and Safari versions?

Line numbers are a feature we'd like to keep; I'll try to implement a fix for iOS/Safari.

**Comment by PenPow** [comment]
> Could you guys provide your iOS and Safari versions?

IOS Version 14.7.1 (Safari version ~= 14, as IOS doesn't give a precise version)

**Comment by DET171** [comment]
> Could you guys provide your iOS and Safari versions?
iOS 14.7.1
Safari 14 as well

**Comment by DET171** [comment]
Helloooo?

**Comment by Danktuary** [comment]
I've given it some thought and decided that this probably isn't necessary.

Vite targets browsers with [esmodule](https://caniuse.com/es6-module)/[dynamic import](https://caniuse.com/es6-module-dynamic-import) compatibility, which is about 93% global according to caniuse, which includes browser versions from 3 years ago or so.
If browser compatibility is a concern, [@vitejs/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) could be included, but to me, this is fine for the guide's purpose and target audience.

PrismJS seems to work fine for us too, as far as I've seen. Shiki doesn't seem needed, and also renders some things differently (e.g. tab indents as 8 spaces).

---

I've pushed a commit to try to fix word wrapping in `pre` tags for Safari browsers (e0c61960e5878d2476e516be32151f187498a792). If it's still bugging for you, let me know.

**Pull request closed without merging**
