### PR TITLE
fix(guide): fix link to command handling

### PR DESCRIPTION
**Pull request by PuneetGopinath**
**Please describe the changes this PR makes and why it should be merged:**
I just made a small fix, sorry, but I did it using the GitHub ui itself, I didn't want to clone this repo for the small change.

### CODE REVIEW

**Comment by SinisterDeveloper** [comment]
@PuneetGopinath It takes you to a 404 page, if you do that

**Comment by SinisterDeveloper** [comment]
image

**Comment by SinisterDeveloper** [comment]
Vuepress's routing requires the folder to be prefixed in the path

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath It takes you to a 404 page, if you do that

Hmm, but even without that it takes you to 404

**Comment by SinisterDeveloper** [comment]
Hmm yes

**Comment by PuneetGopinath** [comment]
> Hmm yes

Hey, it does not come 404 for me

**Comment by PuneetGopinath** [comment]
https://deploy-preview-760--discordjs-guide.netlify.app/command-handling/

**Comment by PuneetGopinath** [comment]
Screenshot_20210804-104622_Chrome Dev

**Comment by SinisterDeveloper** [comment]
@PuneetGopinath 

https://user-images.githubusercontent.com/80232412/128126193-9a00e94b-32f8-4943-ac0b-ea09e6fffcf7.mp4

**Comment by PuneetGopinath** [comment]
Just refresh the page after clicking link. This shouldn't happen, but I don't know why it does

**Comment by WiseDevHelper** [comment]
This links to the wrong page. The paragraph should be rewritten as the page which this link redirects to was removed.

**Comment by PuneetGopinath** [comment]
> This links to the wrong page. The paragraph should be rewritten as the page which this link redirects to was removed.

Oh, okay

**Pull request closed without merging**
