### PR TITLE
feat: Add page on hosting

### PR DESCRIPTION
**Pull request by UndecidedSource**
**Please describe the changes this PR makes and why it should be merged:**
https://github.com/discordjs/guide/projects/1#card-16181111

### CODE REVIEW

**Comment by Danktuary** [comment]
Do you plan on adding steps and details on how to set it up and such? That's the main point I wanted addressed in this page.

**Comment by UndecidedSource** [comment]
> Do you plan on adding steps and details on how to set it up and such? That's the main point I wanted addressed in this page.

Yeah. I'll add an example up setting up a VPS using Vultr

**Comment by RDambrosio016** [comment]
Personally, I believe setting up a VPS is out of the scope of the djs guide. I believe the djs guide should be divided into parts, one which is djs things, and another which includes misc things like sequelize, keyv, and hosting.

**Comment by almostSouji** [comment]
Closing due to ongoing inactivity. If you want to take on this task feel free and please apply https://github.com/discordjs/guide/pull/336#issuecomment-592622261.

**Pull request closed without merging**
