### PR TITLE
Fixing a small bug

### PR DESCRIPTION
**Pull request by FizzesShark**
The current code returns an error, as message.client does not return the list of commands, as the rest of the code seems to assume.

### CODE REVIEW

**Comment by tipakA** [comment]
Uh, that's destructuring, it should work normally

**Comment by didinele** [comment]
uh... what..?

You should research stuff and test them before openning issues y'know.

As far as I know any Node version over 8 supports destructuring.

Here's how it works:
```js
const foo = {
  bar: 'test'
});

const { bar } = foo;

console.log(bar); // test```

[Here's the MDN page on destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring)

**Comment by FizzesShark** [comment]
The reason I changed it was because I tested this on my computer, and it was returning errors as I couldn't call commands.map().

**Comment by tipakA** [comment]
Errors like...

Also, this isn't really place for that, you can join [Discord server](https://discord.gg/bRCvFy9) for easier communication

**Comment by didinele** [comment]
Your... "fix" breaks it even more? Our code right now is the same as doing `message.client.commands` and yours is doing `message.client.commands.commands`

**Pull request closed without merging**
