### PR TITLE
(refactor) Fixing code, Additional Features, More user friendly

### PR DESCRIPTION
**Pull request by 9ebd7134**
Hope you enjoyed my commits :)

**Please describe the changes this PR makes and why it should be merged:**
Using es6 syntax with Javascript, I'll try and compile this with typescript later for additional fixes. 

**More user friendly**
I used message embeds so its more friendly compared to the normal message.reply(text)

**Fixing code**
More reliable code since i compiled some pieces  of the code typescript

**Additional features**
Coming soon

**Requirements**
```
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.23.4",
    "typescript": "^4.3.5"
```

new `colors.json` file

**configs**
.eslintrc.json
```json
{
  "extends": ["airbnb-base", "plugin:@typescript-eslint/recommended"],
  "env": {
    "node": true,
    "es6": true
  },
  "parserOptions": {
    "ecmaVersion": 2021
  },
  "rules": {
    "no-console": "off",
    "linebreak-style": "off",
    "quotes": "off",
    "no-unused-vars": "warn"
  }
}
```

.prettierrc
```json
{
    "trailingComma": "all"
}
```

### CODE REVIEW

**Comment by monbrey** [comment]
No thank you.

- The code is more difficult to read due to the removal of much of white-space
- You added eslint as a dependency, yet decided to ignore the rules almost immediately, which is bad practice.
- Usage of `var` is a bad, outdated practice. The guide's current usage of `let` and `const` is correct.
- You imported a `color.json` file which isn't covered anywhere in the guide and as such, does not exist.
- Your usage of the `MessageEmbed` class is completely incorrect, nor do we wish to recommend that people use embeds at every possible opportunity.

**Review by 1chiSensei — CHANGES_REQUESTED** [review]
no.

**Comment by 9ebd7134** [comment]
> 
> 
> No thank you.
> 
>     * The code is more difficult to read due to the removal of much of white-space
> 
>     * You added eslint as a dependency, yet decided to ignore the rules almost immediately, which is bad practice.
> 
>     * Usage of `var` is a bad, outdated practice. The guide's current usage of `let` and `const` is correct.
> 
>     * You imported a `color.json` file which isn't covered anywhere in the guide and as such, does not exist.
> 
>     * Your usage of the `MessageEmbed` class is completely incorrect, nor do we wish to recommend that people use embeds at every possible opportunity. They are quite often not more user friendly in any way.

 Woops, sorry i didn't config tsconfig properly and the compiled output is a mess, i'll fix them now

**Comment by thehairy** [comment]
I doubt tsconfig will fix that mess.

**Comment by 1chiSensei** [comment]
> > 
> > 
> > No thank you.
> > 
> >     * The code is more difficult to read due to the removal of much of white-space
> > 
> >     * You added eslint as a dependency, yet decided to ignore the rules almost immediately, which is bad practice.
> > 
> >     * Usage of `var` is a bad, outdated practice. The guide's current usage of `let` and `const` is correct.
> > 
> >     * You imported a `color.json` file which isn't covered anywhere in the guide and as such, does not exist.
> > 
> >     * Your usage of the `MessageEmbed` class is completely incorrect, nor do we wish to recommend that people use embeds at every possible opportunity. They are quite often not more user friendly in any way.
> 
>  Woops, sorry i didn't config tsconfig properly and the compiled output is a mess, i'll fix them now

Why even bother using compiled typescript code?

**Comment by 9ebd7134** [comment]
i fixed it .

**Comment by 9ebd7134** [comment]
could i reopen this?

**Comment by thehairy** [comment]
> could i reopen this?

Please dont.

**Pull request closed without merging**
