### PR TITLE
Added hosting with heroku page.

### PR DESCRIPTION
**Pull request by jsmiith**
Added a tutorial on how to start Hosting with Heroku. Thinking on adding one for glitch.com too, amongst other things.

### CODE REVIEW

**Comment by Drahcirius** [comment]
This tutorial is nice and simple, however it doesn't really fit with the rest of the guide. There are a bunch of sections in the guide where we expect you to be able to ssh into the server and run commands. Heroku and other free services intentionally disallow you from doing that, meaning people following this page cannot follow the instructions in some of the other pages of the guide.

Aside from that, the biggest concern that I can see is that if they follow the page in https://discordjs.guide/creating-your-bot/configuration-files.html and they also follow your instruction to run `git add .` they will be committing their config file into their repo which is a security concern that was brought up in https://github.com/discordjs/guide/issues/100. If they had ssh or sftp, they could commit their code but upload their config file manually so that their token doesn't get added to their repository. 

I think in order for a tutorial like this to be added to the guide, it would need to at least have ssh access and be somewhat hosting-platform agnostic. Then we can say that the same instructions will work on digitalocean, vultr, linode, etc.

**Comment by noneissome** [comment]
> This tutorial is nice and simple, however it doesn't really fit with the rest of the guide. There are a bunch of sections in the guide where we expect you to be able to ssh into the server and run commands. Heroku and other free services intentionally disallow you from doing that, meaning people following this page cannot follow the instructions in some of the other pages of the guide.
> 
> Aside from that, the biggest concern that I can see is that if they follow the page in https://discordjs.guide/creating-your-bot/configuration-files.html and they also follow your instruction to run `git add .` they will be committing their config file into their repo which is a security concern that was brought up in #100. If they had ssh or sftp, they could commit their code but upload their config file manually so that their token doesn't get added to their repository.
> 
> I think in order for a tutorial like this to be added to the guide, it would need to at least have ssh access and be somewhat hosting-platform agnostic. Then we can say that the same instructions will work on digitalocean, vultr, linode, etc.

True. It definitely needs some work.

**Comment by almostSouji** [comment]
Going to close this for now due to lack of activity, feel free to reopen if you want to address the issues pointed out by Drahcirius though!

**Comment by Monoverde888** [comment]
> 
> 
> This tutorial is nice and simple, however it doesn't really fit with the rest of the guide. There are a bunch of sections in the guide where we expect you to be able to ssh into the server and run commands. Heroku and other free services intentionally disallow you from doing that, meaning people following this page cannot follow the instructions in some of the other pages of the guide.
> 
> Aside from that, the biggest concern that I can see is that if they follow the page in https://discordjs.guide/creating-your-bot/configuration-files.html and they also follow your instruction to run `git add .` they will be committing their config file into their repo which is a security concern that was brought up in #100. If they had ssh or sftp, they could commit their code but upload their config file manually so that their token doesn't get added to their repository.
> 
> I think in order for a tutorial like this to be added to the guide, it would need to at least have ssh access and be somewhat hosting-platform agnostic. Then we can say that the same instructions will work on digitalocean, vultr, linode, etc.

You CAN do some thing that is like ssh with the heroku cli
`heroku run bash`

**Pull request closed without merging**
