### PR TITLE
Create config.yml

### PR DESCRIPTION
**Pull request by NightYoshi370**
Adds a direct link to Discord Server in the issues page

### CODE REVIEW

**Comment by almostSouji** [comment]
This PR should also remove the current "ask questions" template then

**Comment by NightYoshi370** [comment]
I disagree since you could be asking about the guide itself but I've still done so.

**Comment by almostSouji** [comment]
> I disagree since you could be asking about the guide itself but I've still done so.

You are right! I absolutely missed that use case, although the structure of the template clearly suggests so (and was the one making the PR adding it)

It seems like I mixed it up with the library, where the template indeed only serves the purpose of redirecting questions about the library.

**Comment by NightYoshi370** [comment]
I've added it back and added a link to the library's github repository. This should clarify what goes where

**Comment by almostSouji** [comment]
Thanks for the PR and sorry for the confusion!

**Pull request merged**
